language: go

go:
  - "1.9"
  - "1.10"

install: true

notifications:
  email: false

before_script:
  - go get github.com/gorilla/websocket  # WebSocket for StreamingAPI

script:
  - go test -v ./tests